### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ROOTH4CK3R** [Pure-L0G1C/InstaBurst#1]
Do I need anything for Proxy to make the program work?
The Proxy-ID and password are left blank when I tried to monitor the progress.

**Comment by Ethical-H4CK3R** [comment]
It uses tor to access a proxy IP. It will only send attempts through the Tor network, if it cannot connect to it, it won’t send any attempts. The program is unable to access the Tor network from the network you’re connected to. The issue is on your side and not the program’s.

**Comment by peshoutan** [comment]
Hi, i have an error when i want to execute this command:
$ python instagram.py
And the last line of the error msg is:
ImportError: cannot import PyperclipException
Python and kali versions are true as expected.
How would i solve this error?

**Comment by Ethical-H4CK3R** [comment]
Are you using Python2.7?

**Comment by peshoutan** [comment]
Python version is 2.7.11

**Comment by Ethical-H4CK3R** [comment]
can you display the whole error, I want to read it.

**Comment by peshoutan** [comment]
Traceback (most recent call last) :
File "instagram.py" , line 6, in <module>
     from lib.console import Console
File "/root/InstaBurst/lib/console.py" , line 6, in <module>
     from cmd2 import Cmd
File "/user/local/lib/python2.7/dist-packages/cmd2.py" , line 54, in <module>
     from pyperclip import PyperclipException
ImportError: cannot import name PyperclipExeption
.

**Comment by peshoutan** [comment]
After "in" in line 2 and 7, there is a module between less-than and greater-than signs, thats not shown at top

**Comment by Ethical-H4CK3R** [comment]
try: pip install -I cmd2
Then: pip install -U cmd2

**Comment by Null1408** [comment]
hi

**Comment by Null1408** [comment]
hi
can u create a gmail brute?
it could be great

**Comment by Ethical-H4CK3R** [comment]
@Null1408 I'll look into it when I get around to it.

**Comment by peshoutan** [comment]
Hi and thanks for responses, i`ve sold that problem, but now i have struggle with tor issue too, do you have any suggestions or alternative for that?

**Comment by Ethical-H4CK3R** [comment]
Did you run install.sh?

**Comment by peshoutan** [comment]
Yes, ive done all commands thats mentioned in youtube, but after monitor command, nothing happend, i checked tor, but it cant connect truly

**Comment by Ethical-H4CK3R** [comment]
Maybe something or someone is blocking your access to the Tor network. If I were you I would run down and run a free VPN that allows Tor on my host machine, then try to run the program on the VMware.

**Comment by LioH4CK3R** [comment]
blank proxy and 0 attempt , how can i fix it ?

**Comment by Ethical-H4CK3R** [comment]
Use a VPN on your Windows machine, it might be the program can’t access the
TOR network from your the network you are connected to

>

**Comment by Modifero** [comment]
Sir, is it possible if using windows 10 and python 3.6?
it would be great, surely i won't doubt to dominate.

**Comment by Ethical-H4CK3R** [comment]
The program is written in Python2 it won’t run on Python3, it would but it
requires few changes. I want to make my program usable on Windows, but I
can’t think of a way to control Tor on Windows. I tried writing crawlers to
scrape proxy sites, but it’s hard to find a proxy that is fast and
unblocked. Just give me time, I’m trying to balance school and this git
profile at once.

>

**Comment by LioH4CK3R** [comment]
i already use vpn but my attempt still zero and no proxy

**Comment by Ethical-H4CK3R** [comment]
Some VPN’s don’t allow Tor, so maybe that might be your issue

**Comment by LioH4CK3R** [comment]
@Ethical-H4CK3R im using free account vpnbook , what vpn can i use to make it work?

**Comment by Ethical-H4CK3R** [comment]
I’m not sure, may do a research on what VPN’s allow Tor

**Comment by LioH4CK3R** [comment]
@Ethical-H4CK3R what vpn did you use? thankyou

**Comment by Ethical-H4CK3R** [comment]
I used the paid version of Cyberghost

>

**Comment by LioH4CK3R** [comment]
i already use cyberghost and install tor , but why still my attempts is 0?

**Comment by Ethical-H4CK3R** [comment]
I’m not sure why it isn’t working

>

**Comment by LioH4CK3R** [comment]
how to check wether tor working or not? sorry spamming

**Comment by Ethical-H4CK3R** [comment]
While the program is attempting or trying to in this case, open a new
terminal and run the command ‘service tor status’ and then check to see if
it says tor is active or dead

>

**Comment by Null1408** [comment]
i have a question that the should reset the wifi and then start or what?
when it want to change ip my wireless goes down and up again

**Comment by Ethical-H4CK3R** [comment]
Yeah, I set to restart the network manager after it fails to access the Tor
network because sometimes the network manager can fail

**Comment by NickTehUnicorn** [comment]
For some reason, I get 0 attempts and no proxy and when I run `service tor status` it says active (exited).

**Comment by fshokam** [comment]
I will not be able to do this

root@kali:~/Desktop/InstaBurst-master# python instagram.py
Run: chmod +x install.sh && ./install.sh
root@kali:~/Desktop/InstaBurst-master# chmod +x install.sh
root@kali:~/Desktop/InstaBurst-master# ./install.sh

OK
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.15-3).
python-pip is already the newest version (9.0.1-2.3).
The following packages were automatically installed and are no longer required:
  dh-python python3-distutils python3-lib2to3
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1553 not upgraded.
Requirement already up-to-date: setuptools in /root/.local/lib/python2.7/site-packages
Requirement already up-to-date: python in /usr/lib/python2.7/lib-dynload
Hit:1 http://kali.mirror.garr.it/mirrors/kali kali-rolling InRelease
Reading package lists... Done                                       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php7.0-cgi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php7.0-cgi' has no installation candidate
Collecting cmd2 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f9/6a/0fc7efe26074a214b3b4d26a5a48d54a3c3919b440d5606c99021ed00c44/cmd2-0.8.8-py2.py3-none-any.whl
Collecting PySocks (from -r requirements.txt (line 2))
Collecting requests (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3.5" (from cmd2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl
Collecting six (from cmd2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pyperclip (from cmd2->-r requirements.txt (line 1))
Collecting pyparsing>=2.0.1 (from cmd2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting enum34; python_version < "3.4" (from cmd2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting wcwidth; sys_platform != "win32" (from cmd2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting subprocess32; python_version < "3.0" (from cmd2->-r requirements.txt (line 1))
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Installing collected packages: contextlib2, six, pyperclip, pyparsing, enum34, wcwidth, subprocess32, cmd2, PySocks, certifi, chardet, urllib3, idna, requests
Successfully installed PySocks-1.6.8 certifi-2018.4.16 chardet-3.0.4 cmd2-0.8.8 contextlib2-0.5.5 enum34-1.1.6 idna-2.7 pyparsing-2.2.0 pyperclip-1.6.2 requests-2.19.1 six-1.11.0 subprocess32-3.5.2 urllib3-1.23 wcwidth-0.1.7
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.15-3).
python-pip is already the newest version (9.0.1-2.3).
The following packages were automatically installed and are no longer required:
  dh-python python3-distutils python3-lib2to3
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1553 not upgraded.
Requirement already up-to-date: setuptools in /root/.local/lib/python2.7/site-packages
Requirement already up-to-date: python in /usr/lib/python2.7/lib-dynload
Hit:1 http://kali.mirror.garr.it/mirrors/kali kali-rolling InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php7.0-cgi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php7.0-cgi' has no installation candidate
Collecting cmd2 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f9/6a/0fc7efe26074a214b3b4d26a5a48d54a3c3919b440d5606c99021ed00c44/cmd2-0.8.8-py2.py3-none-any.whl
Collecting PySocks (from -r requirements.txt (line 2))
Collecting requests (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3.5" (from cmd2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl
Collecting six (from cmd2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pyperclip (from cmd2->-r requirements.txt (line 1))
Collecting pyparsing>=2.0.1 (from cmd2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting enum34; python_version < "3.4" (from cmd2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting wcwidth; sys_platform != "win32" (from cmd2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting subprocess32; python_version < "3.0" (from cmd2->-r requirements.txt (line 1))
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Installing collected packages: contextlib2, six, pyperclip, pyparsing, enum34, wcwidth, subprocess32, cmd2, PySocks, certifi, chardet, urllib3, idna, requests
Successfully installed PySocks-1.6.8 certifi-2018.4.16 chardet-3.0.4 cmd2-0.8.8 contextlib2-0.5.5 enum34-1.1.6 idna-2.7 pyparsing-2.2.0 pyperclip-1.6.2 requests-2.19.1 six-1.11.0 subprocess32-3.5.2 urllib3-1.23 wcwidth-0.1.7
root@kali:~/Desktop/InstaBurst-master# 
root@kali:~/Desktop/InstaBurst-master# python instagram.py
Run: chmod +x install.sh && ./install.sh
root@kali:~/Desktop/InstaBurst-master#
