### ISSUE TITLE
Is everything correct. ?

### ISSUE THREAD

**Issue by bitden** [Pure-L0G1C/InstaBurst#12]
It works but I have the feeling that it’s too fast and that it miss a lot of passwords 
For example 

Attempt 100 “xyz”
And then
Attempt 130 “abc”
That happens after a couple of seconds ?

**Comment by Ethical-H4CK3R** [comment]
Yeah, I'm just multithreading, using 16 threads instead of 1. Don't worry It's not going to miss any password; each password gets its own thread, and when it cracks the password will notify the program.
