### ISSUE TITLE
Super mais problème avec tor

### ISSUE THREAD

**Issue by ultimjeanno** [Pure-L0G1C/InstaBurst#13]
Bonsoir
J’ai un soucis, lorsque je lance avec start0 et monitor 0 le service tor me demande de m’authentifier pour démarrer le service. 
Le problème c’est qu’il me le redemande à chaque fois qu’il change d’identité c’est à dire toute les 15 secondes ! 
Une idée pour m’aider à m’en sortir ? 
Merci 
Jean

**Comment by ultimjeanno** [comment]
Hello I have a problem, when I run with start0 and monitor 0 the service tor asks me to authenticate to start the service. The problem is that he asks me every time he changes his identity : every 15 seconds! An idea to help me out? Thank you 
Jean

**Comment by Ethical-H4CK3R** [comment]
I'm not sure.

**Comment by ultimjeanno** [comment]
Ok.. thanks
