### ISSUE TITLE
No 'pass.lst'

### ISSUE THREAD

**Issue by Roadmanus** [Pure-L0G1C/InstaBurst#14]
Hey, I followed your video until the last step which was 'create <username><wordlist>'. Once I typed in the same code as you, it said it could not find the "pass.lst" I doubled check with the Instaburst folder on my desktop and there is no "pass.lst" file.

**Comment by m-henderson** [comment]
You have to manually generate this list and place it into the directory.

**Comment by acilard69** [comment]
can anyone make an example

**Comment by m-henderson** [comment]
@acilard69 were you able to generate the pass.lst?

**Comment by khaham** [comment]
hi
that's happened to me also
what should i do?

**Comment by rawan-al-maawali** [comment]
I don't know to generate the pass.lst, can someone explain?
