### ISSUE TITLE
STARTING RESEARCH 

### ISSUE THREAD

**Issue by dirm02** [Pure-L0G1C/InstaBurst#15]
Starting: 1 ...

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/InstaBurst/lib/bruter.py", line 141, in password_regulator
    with open(self.wordlist, 'r') as wordlist:
IOError: [Errno 21] Is a directory: 'pass.lst'

WHAT DO YOU THINK IS THIS ISSUE?

**Comment by Pure-L0G1C** [comment]
pass.lst isn't a file, you have a folder named pass.lst

**Comment by dirm02** [comment]
Bro ; even so , i created manually pass.lst + when i do monitor 0 or 1 or anything ; this guy is just changing proxy IP but not doind any attempts....

**Comment by dirm02** [comment]
what can I do about it ?

**Comment by Pure-L0G1C** [comment]
The program will do that all the time because they are many bad nodes out there, but it shouldn't be doing that the whole time. I have finals next week so I can't help this weekend, but I will take a look at it next weekend.

**Comment by Pure-L0G1C** [comment]
The error is on his side it seems and not the program. But if you really want to help me, you can improve the console.
