### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by R3nt0n** [Pure-L0G1C/InstaBurst#17]
Why is there a persistent connection to 91.134.XXX.XXX?

Also, can you explain if ngrok  is necessary to bruteforce? I read the code about the phishing feature but you don't talk about it in the doc.

**Comment by R3nt0n** [comment]
It wasn't my intention at all. Reading my post now, I don't whink that I was transmiting that idea, but maybe the title was confuse so I changed it because I dont wanna alarm other users. Think about it, if I didn't trust you, I wouldnt ask you about the issue.

Actually, although Im not interested in bruteforce Instagram accounts, i wanted to help you to improve this tool because i think the idea behind is powerful and appliable to other things. Specifically, i was thinking about how to speed up the proxy changes, so I wanted to know how you were doing it. Then I read [this issue](https://github.com/Pure-L0G1C/InstaBurst/issues/15) and, although this isn't affecting to me (made quick tests and apparently everything works fine), I dive into the connections trying to figure out what could been happening around.

Related to ngronk, I know what is it and that's the reason why i asked you, because if its only related to the phishing feature, i wont need to touch this part.

Sorry if u misunderstood my words. Thank you for share your idea and im here if u need some help.

**Comment by Pure-L0G1C** [comment]
Oh, sorry about that. If you want to really help with the tool, then you can try to improve the console, make it look better, that where I'm having a hard time. 

Also, I was thinking of making this tool Windows compatible, and the only way to do that is by getting rid of the use of TOR and replacing with a proxy scraper. I have a tool that does that called [Inflator](https://github.com/Pure-L0G1C/Inflator), the tool sucks at faking YouTube views, but is really good at finding proxies. 

When this tool starts using normal proxies instead of TOR nodes, then it will able to have a dynamic list of about 30-50 proxies it can go through, instead of only one.

The issue with normal proxies in comparison to TOR proxies is that some normal proxies can be extremely slow. I'm still thinking of a way to figure out the speed before using the proxies, but so far no luck. 

If you really want to help, I really need help making the console part look appealing. At the current moment, I'm using a command line module called cmd2, but it has many issues. So, I was thinking of writing my own console module, which should be able to run on almost every machine.

**Comment by R3nt0n** [comment]
Yes i saw your inflator views tool, didn't try but looks fucking awesome.

Of course it's your choice, but if you ask me, i would focus all the efforts on the speed up improvement rather than portability, specially when it's about Windows. I read somewhere in your repository that it's specially made to run under Kali. Maybe some tweaks to make it general-LINUX compatible would be enough. Anyway, you always be able to make a special version to run under Windows in the future (when the main goals will achieved), with the speed limitations you were talking about,  instead of a unique-version that would limit speed under all operative systems.

Related to console, maybe you can tell me what is what you are thinking about. About the looks-like feeling, i just can think about some improvements over the prompt. About the functionality, i realized that one of the things that cannot do from the script is to change the working directory. I though it makes sense for two reasons: the script need to invokes other tools (such ngrok) or working with directories (such web). If you think that worth to work around it maybe we can store the absolute path where the script is at the beggining of the execution, and when some path is needed, append the relative part to this absolute that we stored to locate the scripts/directories under the script path. Then you will be free to change the working directory. Another thing to point is that it has to be done with os.chdir() instead of subprocess because the later spawn a new process instead of change the current's enviroment. I don't know how far do you wanna go with this semi-shell inside the script, but again I would focus on the speed up improvement haha. Anyway, if you can be more specific about the things you would like to improve on the console, i would like to help.

**Comment by R3nt0n** [comment]
The proxy changes are made by restarting the tor service, what if we enable the control port and renew the ip through it? Looks like it's a bit faster, but could be significant. I'm just throwing it, maybe you already have tried it and discard for other reasons.

```
# time echo -e 'AUTHENTICATE ""\r\nsignal NEWNYM\r\nQUIT' | nc 127.0.0.1 9051
250 OK
250 OK
250 closing connection

real	0m0,007s
user	0m0,001s
sys	0m0,004s

# time service tor restart

real	0m0,093s
user	0m0,006s
sys	0m0,010s
```

**Comment by Pure-L0G1C** [comment]
I never tried that method, I don't even know how it would work. Do mind explaining it to me?

**Comment by R3nt0n** [comment]
Sure, the control port allows you to configure Tor trough commands. To enable it you have to edit the file `torrc`, uncommenting two lines: `ControlPort 9051` (u can change the port if u want) and `CookieAuthentication 0` (set it to 0 by now, maybe in the future you can introduce in your tool a conf file to allows the user set his own port and hashed password).

Now, if you restart the Tor service and run `ss -tlnp`, u can see that there's a listener on the 9051 port. Basically you connect trough telnet, netcat or whatever and send commands to change Tor configuration.

`signal NEWNYM` is the command to renew the Tor circuits. You can confirm that running `torify curl ifconfig.co` before and after.


Here you have a complete explanation about what yo can do through the control port:
https://www.thesprawl.org/research/tor-control-protocol/
