### ISSUE TITLE
cant catch proxy ip

### ISSUE THREAD

**Issue by maXi-star** [Pure-L0G1C/InstaBurst#19]
wont work this dayz . I hadnt this problem before .
so is there a problem on my connection or tor nodes etc ?

**Comment by maXi-star** [comment]
it was connection prob.

**Comment by wasp478** [comment]
I think I got same problem. It never starts to connect proxies. I'm figuring out why. Maybe cause of tor or anything like that. Please let us know if any guys having same issues.
