### ISSUE TITLE
Run: chmod +x install.sh && ./install.sh

### ISSUE THREAD

**Issue by groovylsd** [Pure-L0G1C/InstaBurst#22]
Every time I try to python instagram.py 

It shows the error Run: chmod +x install.sh && ./install.sh

I run it and it still doesn't do anything what does this mean ? Pleasee help

**Comment by Pilly170** [comment]
I have the same, ran the install. then thereafter "Run: chmod +x install.sh && ./install.sh" even though install.sh is chmodded correctly.
