### ISSUE TITLE
'thing' that allows you to open two or more sessions per user

### ISSUE THREAD

**Issue by artomweb** [Pure-L0G1C/InstaBurst#24]
If you create to sessions and rename one of them to be the same as the other, you can have two operating sessions for one username. It still executes fine but I am wondering if it will cause Instagram to lock down on what is happening. Other codes that I have tested have strictly declared in their setup that only one session is allowed per user, and you have code in place to prevent people from creating two sessions under the same username the normal way.

**Comment by Pure-L0G1C** [comment]
No. It will just create redundant attempts A.KA time wasting.
