### ISSUE TITLE
Without changing proxy?

### ISSUE THREAD

**Issue by sickjoe912** [Pure-L0G1C/InstaBurst#25]
Is it possible to provide a version of the program that doesn't deal with proxies or anything? I am just testing it on my own account for research, education, etc and I'm not trying to stay anonymous at the moment. I've had a dig through bruter.py and, correct me if I'm wrong, but removing everything to do with proxies should make the program run faster? If not please educate me - It's been running for an hour or two and only checked 3000 passwords whereas aircrack-ng did the entire rockyou.txt in just under 40 mins.

Amazing work though, thanks.

**Comment by Pure-L0G1C** [comment]
If you remove that source code that deals with proxies, then your IP
address will be blacklisted after trying 16 passwords.

**Comment by sickjoe912** [comment]
Don't close it, I need help

**Comment by Pure-L0G1C** [comment]
Look, if the IP address isn't changed after every 16 attempts Instagram will ignore any requests sent from your IP for about 10 minutes. So, don't mess with the proxy settings.
