### ISSUE TITLE
Distribution Dependency

### ISSUE THREAD

**Issue by Naheel-Azawy** [Pure-L0G1C/InstaBurst#30]
Hi,
The readme page says that it requires Kali Linux which is something a bit unusual to have the entire distribution in your requirements! Also you install.sh uses apt-get ignoring the fact that other might want to use it where apt is not there.
Can you please specify what dependencies exactly are you using from Kali so that others can find the packages for their own distributions easier?

And thanks for you great work!

**Comment by Pure-L0G1C** [comment]
Well I programmed and tested it only in Kali. Bysides you should be used the [updated version](https://github.com/Pure-L0G1C/Instagram), it's like a million times faster and it can run on almost any OS

**Comment by Naheel-Azawy** [comment]
@Pure-L0G1C Sweet! Thanks!
