### ISSUE TITLE
Crack not starting

### ISSUE THREAD

**Issue by CancerKidMaxxx** [Pure-L0G1C/InstaBurst#31]
Hello, When im trying to start the cracking of an account it says it isn't active.

![image](https://user-images.githubusercontent.com/42348705/52564424-73429100-2e04-11e9-815d-a402309e9a04.png)

**Comment by Pure-L0G1C** [comment]
Dude I don’t maintain this program anymore, use the other code instead

**Comment by CancerKidMaxxx** [comment]
Which other Code?

**Comment by Pure-L0G1C** [comment]
The one that’s named Instagram

**Comment by CancerKidMaxxx** [comment]
Can you give me a link?

**Comment by Pure-L0G1C** [comment]
https://github.com/Pure-L0G1C/Instagram

**Comment by CancerKidMaxxx** [comment]
Thanks
