### ISSUE TITLE
Trying to run instagram.py

### ISSUE THREAD

**Issue by ZeldaM** [Pure-L0G1C/InstaBurst#4]
I'm trying to run python instagram.py  but instead I get this message

$ python instagram.py
Traceback (most recent call last):
  File "instagram.py", line 5, in <module>
    from lib.tor import tor_exists
  File "C:\Users\karen\Instaburst\lib\tor.py", line 6, in <module>
    from commands import getoutput as shell
ModuleNotFoundError: No module named 'commands'

**Comment by Ethical-H4CK3R** [comment]
The program is only for Kali Linux not Windows

**Comment by ZeldaM** [comment]
Even if I downloaded Kali linux?

**Comment by ZeldaM** [comment]
I was able to run the entire program up to where I am supposed to put the pass.lst
However every time I type "create (person's username) and the txt file, the program is unable to find it. 
How can I fix this?

**Comment by Ethical-H4CK3R** [comment]
Are you providing the correct path to the wordlist?

>

**Comment by ZeldaM** [comment]
I tried, but the program kept saying it is unable to find it.
Now I am having an issue of kali linux not being able to read the CPU table?

**Comment by Ethical-H4CK3R** [comment]
I believe the issue is your computer and not the program

**Comment by groovylsd** [comment]
Run: chmod +x install.sh && ./install.sh 

every time I try to python instagram.py 

It shows the error on top helpp
