### ISSUE TITLE
How can I use it on Ubuntu?

### ISSUE THREAD

**Issue by JWENSOULS** [Pure-L0G1C/InstaBurst#6]
I'm sure that is possible

**Comment by Ethical-H4CK3R** [comment]
I don’t use Ubuntu, so I’m not sure.

>

**Comment by Ethical-H4CK3R** [comment]
It’s not impossible to do. You would need to modify the code in few places
and it would work. I’m not sure, but my guess is that only the installation
process would need to be modified.
