### ISSUE TITLE
what I missed !

### ISSUE THREAD

**Issue by x1ox** [Pure-L0G1C/InstaBurst#7]
what i missed ! ..
root> help

	Possible Commands (type help <command>)

+-------------------------------------------------------------------------+
capture_list database monitor remove start_phish
change_username delete queue reset stop
change_wordlist exit quit restart stop_phish
create get_banner recreate start

root> capture_list
root> start_phish

[+] Starting social engineering attack ...

[!] Error: Phishing attack failed, try again in a while!

**Comment by Ethical-H4CK3R** [comment]
An example of lazy programming. I got too lazy to test the new feature because I had a ton of school work due that week, and I didn't wanted to waste too much time on a hobby. The problem occurs when requests fails to return a link. If you don't mind, comment out lines 42 and 47 in the file ngrok.py and restart the program, if the error occurs again, show it to me. I will take a look at the code this weekend.

**Comment by x1ox** [comment]
Thanx for your  fast answer and I ask Allah to give you what you ask  and what you want
But sorry bro I don't know any thing about what you said  
I don't know any thing about programming 
This is my first week in kali linux I'm under beginners  😓

**Comment by Ethical-H4CK3R** [comment]
Thanks man, I will try my best to debug it and fix it over this weekend.

>

**Comment by x1ox** [comment]
what happen bro ? did you remember to fix it

**Comment by Ethical-H4CK3R** [comment]
Chill man, it’s only 1 AM right now. Give me at least few hours to relax,
recharge and forget about school, then I’ll work on it.

**Comment by x1ox** [comment]
thanks man > I like your codes its always work fine

**Comment by Ethical-H4CK3R** [comment]
Thanks. Check if it works now, I just did an update.

**Comment by x1ox** [comment]
same Error :(

After    ./install.sh  i get this note >

root@kali:~/InstaBurst# ./install.sh
OK
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.14-4).
python-pip is already the newest version (9.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 31 not upgraded.
Requirement already up-to-date: setuptools in /usr/lib/python3/dist-packages
Collecting python


 **# { Could not find a version that satisfies the requirement python (from versions: )
No matching distribution found for python }**

but it complete installing 

and i can run it but i get same Error  when i start phishing 

root> start_phish

[+] Starting social engineering attack ...

[!] Error: Phishing attack failed, try again in a while!

**Comment by Ethical-H4CK3R** [comment]
The program should have created a log file, if that log file is empty then it might your computer and not the program. You should reinstall python 2.7 and get rid of python3.

**Comment by wizardgandalf** [comment]
Traceback (most recent call last):
  File "instagram.py", line 6, in <module>
    from lib.console import Console
  File "/data/data/com.termux/files/home/InstaBurst/lib/console.py", line 7, in <module>
    from cmd2 import Cmd
ImportError: No module named cmd2

How to solve this problem?

**Comment by Abbeyly** [comment]
I can't find line 42 and 47 as stated cause the editor don't name in numbers
